--- doc/models/Makefile
+++ doc/models/Makefile
@@ -297,6 +301,12 @@
 	$(SRC)/netanim/doc/figures/RoutingTables.pdf \
 	$(SRC)/netanim/doc/figures/PacketTimeline.png \
 	$(SRC)/netanim/doc/figures/PacketTimeline.pdf \
+	$(SRC)/ofswitch13/doc/source/figures/ofswitch13-controller.eps \
+	$(SRC)/ofswitch13/doc/source/figures/ofswitch13-library.eps \
+	$(SRC)/ofswitch13/doc/source/figures/ofswitch13-module.eps \
+	$(SRC)/ofswitch13/doc/source/figures/ofswitch13-qos-topology.eps \
+	$(SRC)/ofswitch13/doc/source/figures/ofswitch13-queue.eps \
+	$(SRC)/ofswitch13/doc/source/figures/ofswitch13-switch.eps \
 	$(SRC)/spectrum/doc/spectrum-channel-phy-interface.png \
 	$(SRC)/spectrum/doc/spectrum-channel-phy-interface.pdf \
 	$(SRC)/spectrum/doc/spectrum-analyzer-example.eps \
@@ -396,6 +406,12 @@
 	$(FIGURES)/lr-wpan-primitives.eps \
 	$(FIGURES)/lr-wpan-data-example.eps \
 	$(FIGURES)/lr-wpan-arch.eps \
+	$(FIGURES)/ofswitch13-controller.eps \
+	$(FIGURES)/ofswitch13-library.eps \
+	$(FIGURES)/ofswitch13-module.eps \
+	$(FIGURES)/ofswitch13-qos-topology.eps \
+	$(FIGURES)/ofswitch13-queue.eps \
+	$(FIGURES)/ofswitch13-switch.eps \
 	$(FIGURES)/802-15-4-ber.eps \
 	$(FIGURES)/802-15-4-per-sens.eps \
 	$(FIGURES)/802-15-4-psr-distance.eps \
@@ -463,6 +479,12 @@
 $(FIGURES)/spectrum-tv-rand-geo-points.pdf_width = 8cm
 $(FIGURES)/lr-wpan-primitives.pdf_width = 3in
 $(FIGURES)/lr-wpan-arch.pdf_width = 2in
+$(FIGURES)/ofswitch13-controller.pdf_width = 10cm
+$(FIGURES)/ofswitch13-library.pdf_width = 14cm
+$(FIGURES)/ofswitch13-module.pdf_width = 14cm
+$(FIGURES)/ofswitch13-qos-topology.pdf_width = 12cm
+$(FIGURES)/ofswitch13-queue.pdf_width = 10cm
+$(FIGURES)/ofswitch13-switch.pdf_width = 10cm
 $(FIGURES)/clear-channel.pdf_width = 12cm
 $(FIGURES)/nist-frame-success-rate.pdf_width = 12cm
 $(FIGURES)/nist-frame-success-rate-n.pdf_width = 12cm
