# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('virt-5gc-example', ['virt-5gc'])
    obj.source = 'virt-5gc-example.cc'

